layout_spectrum: 0.5075188
color:
  saturation: 0.7937468
  lightness: 0.7263401
  brandStrength: 0.9966305
  rhythmicContrast: 0.5157255
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.3335837
name: HowItCame
